export const SET_LOCATION = 'SET_LOCATION';

export const SET_USER = 'SET_USER';
export const SET_FULL_NAME = 'SET_FULL_NAME';
export const ADD_INVITED_AMOUNT = 'ADD_INVITED_AMOUNT';
export const MINUS_INVITED_AMOUNT = 'MINUS_INVITED_AMOUNT';
export const SET_DEVICE_TOKEN = 'SET_DEVICE_TOKEN';
export const SET_NOTIFY_REGION = 'SET_NOTIFY_REGION';
export const SET_INVITED_AMOUNT = 'SET_INVITED_AMOUNT';
export const SET_PARTICIPATED_AMOUNT = 'SET_PARTICIPATED_AMOUNT';
export const ADD_PARTICIPATED_AMOUNT = 'ADD_PARTICIPATED_AMOUNT';
export const MINUS_PARTICIPATED_AMOUNT = 'MINUS_PARTICIPATED_AMOUNT';

export const SET_FILTER = 'SET_FILTER';

export const INITIALIZE_FILTER = 'INITIALIZE_FILTER';
export const SET_SORT_BY = 'SET_SORT_BY';

export const SET_NOTIFICATION_REDIRECT = 'SET_NOTIFICATION_REDIRECT';

export const CANCEL_PRAYER = 'CANCEL_PRAYER';
