export const SET_LOCATION = 'SET_LOCATION';

export const SET_USER = 'SET_USER';
export const SET_FULL_NAME = 'SET_FULL_NAME';
export const ADD_INVITED_AMOUNT = 'ADD_INVITED_AMOUNT';

export const SET_FILTER = 'SET_FILTER';

export const INITIALIZE_FILTER = 'INITIALIZE_FILTER';
export const SET_SORT_BY = 'SET_SORT_BY';

export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const SET_IS_NEW_NOTIFICATION = 'SET_IS_NEW_NOTIFICATION';
export const SET_NOTIFICATION_REDIRECT = 'SET_NOTIFICATION_REDIRECT';
